# Level 1

In [1]:
import pandas as pd

In [2]:
te = pd.read_csv("Data/training_data.csv", names=["sequence", "class"])
te

sequence  class
0     fgiadcfabdhiecgcefhfefeeciedcb      3
1     bghfcdbaecdfgiadafaieicihdccbe      4
2     agidfedadgcaaeieccabcdbahgcdeh      1
3     gchcdfcghghhcfghbbeicfcdecfgbg      2
4     hgbdghafccgchicaafgdcagcdfcbbe      2
...                              ...    ...
5452  behadefgfhcibdicddeibaafaigcgd      4
5453  dfffiehccefecifcceifgdeieghbcb      3
5454  hbbcddahicggbfiiegefbibbegegge      1
5455  caciabgddgdbefibhbcdehhbhgieib      1
5456  bigdgaedgcdhcbdegbicbbeiedefec      2

[5457 rows x 2 columns]

In [3]:
te["length"] = te["sequence"].apply(len)

In [4]:
te["class"].value_counts().sort_index()

0    1182
1    1053
2    1002
3    1214
4    1006
Name: class, dtype: int64

# Level 2

In [5]:
te.loc[te["length"] == 30]["class"].value_counts().sort_index()

0    1133
1    1020
2     965
3    1181
4     976
Name: class, dtype: int64

# Level 3

In [6]:
train = pd.read_csv("Data/training_data.csv", names=["sequence", "class"])
train.head()

sequence  class
0  fgiadcfabdhiecgcefhfefeeciedcb      3
1  bghfcdbaecdfgiadafaieicihdccbe      4
2  agidfedadgcaaeieccabcdbahgcdeh      1
3  gchcdfcghghhcfghbbeicfcdecfgbg      2
4  hgbdghafccgchicaafgdcagcdfcbbe      2

In [7]:
train_clean = train.loc[train["class"] <=1 ]
train_clean.head()

sequence  class
2   agidfedadgcaaeieccabcdbahgcdeh      1
5   febcfhggcbgaaidbagbbdgbfdcccid      0
7   aidiicbbefghdcdhgccheebeehefcf      0
8   igihfghgdbfaahfbcdegheefdgidii      1
11  eifaidbagbeidhhgggiddcbcdfibhf      0

In [8]:
import sklearn
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [9]:
X = train_clean["sequence"].apply(lambda x: pd.Series(list(x))).drop(columns=[30, 31, 32])
X

0  1  2  3  4  5  6  7  8  9   ... 20 21 22 23 24 25 26 27 28 29
2     a  g  i  d  f  e  d  a  d  g  ...  c  d  b  a  h  g  c  d  e  h
5     f  e  b  c  f  h  g  g  c  b  ...  d  g  b  f  d  c  c  c  i  d
7     a  i  d  i  i  c  b  b  e  f  ...  e  e  b  e  e  h  e  f  c  f
8     i  g  i  h  f  g  h  g  d  b  ...  h  e  e  f  d  g  i  d  i  i
11    e  i  f  a  i  d  b  a  g  b  ...  d  c  b  c  d  f  i  b  h  f
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
5449  e  c  a  h  f  h  b  b  g  e  ...  i  b  g  g  g  d  h  i  i  h
5450  i  c  f  c  b  c  d  c  b  h  ...  i  e  g  e  i  b  i  h  e  i
5451  h  b  d  d  b  c  i  d  h  d  ...  d  b  b  c  b  g  c  i  i  b
5454  h  b  b  c  d  d  a  h  i  c  ...  b  i  b  b  e  g  e  g  g  e
5455  c  a  c  i  a  b  g  d  d  g  ...  e  h  h  b  h  g  i  e  i  b

[2235 rows x 30 columns]

In [10]:
test = pd.read_csv("Data/simple_test_data.csv",  names=["sequence", "class"])
test.head()

sequence  class
0  eccbbdabcdhehibfhihihihebifcbi    NaN
1  ibbfgdeiibcdighbcgegefbihhbhge    NaN
2  iebcdfahebhedhhdegghgcfdgefhfb    NaN
3  dchbabigcehaaaidfgdbgbiehedehg    NaN
4  hfaagdbcdiihdffedefgbciccgdfch    NaN

In [11]:
enc = sklearn.preprocessing.OneHotEncoder()
enc.fit(X)
X = enc.transform(X).toarray()
X

array([[1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [12]:
clf = RandomForestClassifier()
clf.fit(X, train_clean["class"])

RandomForestClassifier()

In [13]:
X_test = test["sequence"].apply(lambda x: pd.Series(list(x)))
X_test = enc.transform(X_test).toarray()
X_test

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]])

In [14]:
y_hat = clf.predict(X_test)
y_hat.tolist()

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,


In [15]:
f = open("level_3_submission.csv", "a")
for i in y_hat.tolist():
    f.write(str(i) + "\n")
f.close()

# level 4

In [16]:
train = pd.read_csv("Data/training_data.csv", names=["sequence", "class"])
train.head()
X = train["sequence"].apply(lambda x: pd.Series(list(x))).drop(columns=[30, 31, 32])
X

0  1  2  3  4  5  6  7  8  9   ... 20 21 22 23 24 25 26 27 28 29
0     f  g  i  a  d  c  f  a  b  d  ...  e  f  e  e  c  i  e  d  c  b
1     b  g  h  f  c  d  b  a  e  c  ...  e  i  c  i  h  d  c  c  b  e
2     a  g  i  d  f  e  d  a  d  g  ...  c  d  b  a  h  g  c  d  e  h
3     g  c  h  c  d  f  c  g  h  g  ...  c  f  c  d  e  c  f  g  b  g
4     h  g  b  d  g  h  a  f  c  c  ...  c  a  g  c  d  f  c  b  b  e
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
5452  b  e  h  a  d  e  f  g  f  h  ...  b  a  a  f  a  i  g  c  g  d
5453  d  f  f  f  i  e  h  c  c  e  ...  g  d  e  i  e  g  h  b  c  b
5454  h  b  b  c  d  d  a  h  i  c  ...  b  i  b  b  e  g  e  g  g  e
5455  c  a  c  i  a  b  g  d  d  g  ...  e  h  h  b  h  g  i  e  i  b
5456  b  i  g  d  g  a  e  d  g  c  ...  b  b  e  i  e  d  e  f  e  c

[5457 rows x 30 columns]

In [17]:
clf = RandomForestClassifier()
enc = sklearn.preprocessing.OneHotEncoder()
enc.fit(X)
X_train = enc.transform(X).toarray()
clf = RandomForestClassifier()
clf.fit(X_train, train["class"])


RandomForestClassifier()

In [18]:
test = pd.read_csv("Data/full_test_data.csv",  names=["sequence", "class"])
test.head()

sequence  class
0  fddigbdhgdheeebhggihcdgcbciihb    NaN
1  aefiffhgbfhecfcefbgibchedfeiig    NaN
2  agaiggbhbiciafedgibicgechcefde    NaN
3  eihfcdigcadhfaibfefhgggcchigef    NaN
4  eegaecdgfhdegfaiedddbcgcbfhfbi    NaN

In [19]:
X_test = test["sequence"].apply(lambda x: pd.Series(list(x)))
X_test = enc.transform(X_test).toarray()
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
y_hat = clf.predict(X_test)
y_hat.tolist()

[0,
 3,
 0,
 0,
 4,
 0,
 4,
 4,
 0,
 1,
 3,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 1,
 0,
 0,
 0,
 3,
 3,
 2,
 2,
 3,
 2,
 4,
 1,
 1,
 0,
 3,
 2,
 3,
 1,
 1,
 2,
 2,
 3,
 0,
 0,
 4,
 4,
 3,
 4,
 4,
 4,
 1,
 2,
 4,
 3,
 0,
 3,
 3,
 2,
 0,
 4,
 2,
 3,
 3,
 4,
 0,
 0,
 0,
 3,
 0,
 3,
 0,
 0,
 3,
 1,
 3,
 1,
 3,
 1,
 4,
 3,
 0,
 2,
 0,
 2,
 3,
 1,
 4,
 2,
 3,
 0,
 3,
 4,
 1,
 3,
 1,
 2,
 0,
 0,
 3,
 3,
 3,
 4,
 1,
 0,
 3,
 4,
 0,
 1,
 3,
 3,
 2,
 1,
 1,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 4,
 4,
 0,
 0,
 3,
 0,
 4,
 0,
 0,
 3,
 3,
 4,
 3,
 0,
 0,
 1,
 0,
 3,
 3,
 3,
 0,
 0,
 4,
 4,
 1,
 0,
 3,
 0,
 0,
 0,
 1,
 3,
 3,
 3,
 4,
 1,
 3,
 4,
 4,
 0,
 0,
 0,
 3,
 1,
 2,
 2,
 4,
 4,
 4,
 3,
 3,
 3,
 2,
 3,
 3,
 1,
 4,
 0,
 1,
 3,
 1,
 3,
 3,
 3,
 0,
 1,
 4,
 0,
 0,
 1,
 4,
 3,
 4,
 2,
 0,
 3,
 0,
 2,
 0,
 4,
 3,
 3,
 0,
 0,
 0,
 4,
 0,
 4,
 0,
 1,
 0,
 1,
 4,
 1,
 0,
 4,
 3,
 0,
 1,
 4,
 3,
 4,
 4,
 3,
 3,
 0,
 4,
 1,
 1,
 3,
 4,
 2,
 2,
 4,
 0,
 0,
 3,
 3,
 2,
 1,
 2,
 3,
 1,
 3,
 2,
 3,
 0,
 2,
 1,
 3,
 1,
 0,


In [21]:
f = open("level_4_submission.csv", "a")
for i in y_hat.tolist():
    f.write(str(i) + "\n")
f.close()

# Level 5

In [22]:
train = pd.read_csv("Data/training_data.csv",  names=["sequence", "class"])
train.head()

sequence  class
0  fgiadcfabdhiecgcefhfefeeciedcb      3
1  bghfcdbaecdfgiadafaieicihdccbe      4
2  agidfedadgcaaeieccabcdbahgcdeh      1
3  gchcdfcghghhcfghbbeicfcdecfgbg      2
4  hgbdghafccgchicaafgdcagcdfcbbe      2

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.utils import class_weight

X_new_train, X_new_test, y_new_train, y_new_test = train_test_split(X_train, train["class"], test_size=0.20, random_state=42)

In [24]:

classes_weights = class_weight.compute_sample_weight(
    class_weight='balanced',
    y=train["class"]
)
len(classes_weights)

5457

In [25]:
smallest_class_count = train["class"].sum()
largest_class_count = len(train["class"]) - smallest_class_count
spw = largest_class_count / smallest_class_count
print(spw)

-0.49109391028630045


In [26]:
from xgboost import XGBClassifier

classes_weights = class_weight.compute_sample_weight(
    class_weight='balanced',
    y=y_new_train
)

clf = XGBClassifier(booster='gbtree', 
   			objective='multi:softmax',
			num_class=5, 
   			max_depth=30, learning_rate=0.1, 
  			n_estimators=105, 
  			scale_pos_weight=spw, 
  			random_state=101, 
            n_jobs=-1, 
			sample_weight=classes_weights,
			eval_metric="aucpr")

clf.fit(X_new_train, y_new_train, sample_weight=classes_weights)

# make predictions
preds = clf.predict(X_new_test)
print(classification_report(y_new_test, preds))

[21:11:27] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:576: 
Parameters: { "sample_weight", "scale_pos_weight" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




C:\Users\danij\anaconda3\envs\CCC\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
C:\Users\danij\anaconda3\envs\CCC\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


              precision    recall  f1-score   support

           0       0.95      0.91      0.93       251
           1       0.92      0.83      0.87       200
           2       0.88      0.91      0.90       188
           3       0.93      0.98      0.95       248
           4       0.97      1.00      0.98       205

    accuracy                           0.93      1092
   macro avg       0.93      0.93      0.93      1092
weighted avg       0.93      0.93      0.93      1092



In [27]:
classes_weights = class_weight.compute_sample_weight(
    class_weight='balanced',
    y=train["class"]
)

clf = XGBClassifier(booster='gbtree', 
   			objective='multi:softmax',
			num_class=5, 
   			max_depth=30, learning_rate=0.1, 
  			n_estimators=105, 
  			scale_pos_weight=spw, 
  			random_state=101, 
            n_jobs=-1, 
			sample_weight=classes_weights,
			eval_metric="aucpr")

clf.fit(X_train, train["class"], sample_weight=classes_weights)

# make predictions
preds = clf.predict(X_test)

[21:11:38] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:576: 
Parameters: { "sample_weight", "scale_pos_weight" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




C:\Users\danij\anaconda3\envs\CCC\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


In [28]:
f = open("level_5_submission.csv", "a")
for i in preds.tolist():
    f.write(str(i) + "\n")
f.close()